[package]
name = "lambda_actix_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-http = "3.3.0"
actix-service = "2.0.2"
lambda-web = { version = "0.2.1", features=["actix4"] }
lambda_runtime = "0.7.3"
aws_lambda_events = "0.7.3"

serde_json = "1.0.91"